// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240303003928_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cep");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Cep", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.MunicipioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CodIBGE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UfId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CodIBGE");

                    b.HasIndex("UfId");

                    b.ToTable("Municipio", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Uf", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41a45a39-6175-4a63-8f99-d796e1d03e97"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6147),
                            Nome = "Acre",
                            Sigla = "AC"
                        },
                        new
                        {
                            Id = new Guid("5747e649-9a39-476e-88d3-2295d9e59e6d"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6159),
                            Nome = "Alagoas",
                            Sigla = "AL"
                        },
                        new
                        {
                            Id = new Guid("7c3cf2b8-6e61-4c29-aa75-107d7d3bde56"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6161),
                            Nome = "Amapá",
                            Sigla = "AP"
                        },
                        new
                        {
                            Id = new Guid("bc60d57e-87ad-4ab0-a37e-29c0f2f3f1e2"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6164),
                            Nome = "Amazonas",
                            Sigla = "AM"
                        },
                        new
                        {
                            Id = new Guid("d0f11c90-23e8-4388-98b0-99c02fdd1963"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6166),
                            Nome = "Bahia",
                            Sigla = "BA"
                        },
                        new
                        {
                            Id = new Guid("f0058a0a-1594-484a-9b23-02cb85d3bd1e"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6168),
                            Nome = "Ceará",
                            Sigla = "CE"
                        },
                        new
                        {
                            Id = new Guid("2347ae36-8725-4644-a5db-9c16f3dd90b5"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6170),
                            Nome = "Distrito Federal",
                            Sigla = "DF"
                        },
                        new
                        {
                            Id = new Guid("8fc1401b-7b83-4eac-bd40-87f8264c245e"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6172),
                            Nome = "Espírito Santo",
                            Sigla = "ES"
                        },
                        new
                        {
                            Id = new Guid("08b05eb3-0984-41d4-b727-605b6b2584c2"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6173),
                            Nome = "Goiás",
                            Sigla = "GO"
                        },
                        new
                        {
                            Id = new Guid("4ad9b3bc-8260-4e2a-a14e-b59e16909a77"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6175),
                            Nome = "Maranhão",
                            Sigla = "MA"
                        },
                        new
                        {
                            Id = new Guid("3c0ff789-0d2a-43cc-b067-44c2b4b1f30a"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6177),
                            Nome = "Mato Grosso",
                            Sigla = "MT"
                        },
                        new
                        {
                            Id = new Guid("1b5900b7-44ff-4a01-a1d8-c6eb4f5ab2aa"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6179),
                            Nome = "Mato Grosso do Sul",
                            Sigla = "MS"
                        },
                        new
                        {
                            Id = new Guid("b84760c3-efdb-4815-826e-50d529a4254c"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6181),
                            Nome = "Minas Gerais",
                            Sigla = "MG"
                        },
                        new
                        {
                            Id = new Guid("6dd67a6c-2f0d-4b32-b535-9c4075745f81"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6182),
                            Nome = "Pará",
                            Sigla = "PA"
                        },
                        new
                        {
                            Id = new Guid("ab48a0b4-2179-4a15-8a5c-6e54a2d37bfc"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6184),
                            Nome = "Paraíba",
                            Sigla = "PB"
                        },
                        new
                        {
                            Id = new Guid("8fd4f242-8fb1-4499-97b0-2c7f33b12212"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6186),
                            Nome = "Paraná",
                            Sigla = "PR"
                        },
                        new
                        {
                            Id = new Guid("7a824d07-25ec-49b7-b891-1a9f5f3e6b10"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6188),
                            Nome = "Pernambuco",
                            Sigla = "PE"
                        },
                        new
                        {
                            Id = new Guid("43f98b8b-3aa2-4f91-8fb6-16c98fd41a14"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6190),
                            Nome = "Piauí",
                            Sigla = "PI"
                        },
                        new
                        {
                            Id = new Guid("e0a6a60f-1b53-4c19-836f-7a071d1e91b1"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6191),
                            Nome = "Rio de Janeiro",
                            Sigla = "RJ"
                        },
                        new
                        {
                            Id = new Guid("b821b87b-0408-4665-8421-73d45a09dd54"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6193),
                            Nome = "Rio Grande do Norte",
                            Sigla = "RN"
                        },
                        new
                        {
                            Id = new Guid("97df85b3-cd25-4632-a356-aa9bde9cb593"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6195),
                            Nome = "Rio Grande do Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            Id = new Guid("8fd3c5ae-88b2-4e5c-b07b-009fb86bb6c2"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6197),
                            Nome = "Rondônia",
                            Sigla = "RO"
                        },
                        new
                        {
                            Id = new Guid("d9613a3a-1d62-4491-950f-d29cd1f89d5d"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6200),
                            Nome = "Roraima",
                            Sigla = "RR"
                        },
                        new
                        {
                            Id = new Guid("22df83df-8233-44ac-8f60-2bfa9d0dcd1c"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6202),
                            Nome = "Santa Catarina",
                            Sigla = "SC"
                        },
                        new
                        {
                            Id = new Guid("4fb7709a-d3b7-4e43-8104-e34b22fa2a2e"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6204),
                            Nome = "São Paulo",
                            Sigla = "SP"
                        },
                        new
                        {
                            Id = new Guid("3b1219b4-4887-40ed-87a3-59b1b9c02e09"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6206),
                            Nome = "Sergipe",
                            Sigla = "SE"
                        },
                        new
                        {
                            Id = new Guid("ba138af0-22a5-4b58-97d1-835b2566dcb3"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(6207),
                            Nome = "Tocantins",
                            Sigla = "TO"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8437e6f6-e9e3-4848-b5c4-6bf3424f1fa9"),
                            CreateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(5925),
                            Email = "admin@admin.com",
                            Name = "Administrador",
                            UpdateAt = new DateTime(2024, 3, 2, 21, 39, 28, 464, DateTimeKind.Local).AddTicks(5950)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.MunicipioEntity", "Municipio")
                        .WithMany("Ceps")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Api.Domain.Entities.MunicipioEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.UfEntity", "Uf")
                        .WithMany("Municipios")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("Api.Domain.Entities.MunicipioEntity", b =>
                {
                    b.Navigation("Ceps");
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Navigation("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
